services:
  init-kafka:
    image: confluentinc/cp-kafka:7.6.1
    depends_on:
      kafka-broker-1:
        condition: service_healthy
      kafka-broker-2:
        condition: service_healthy
      kafka-broker-3:
        condition: service_healthy
    entrypoint: ["/bin/bash", "-euc"]
    command:
      - |
        for topic in \
          payment-request \
          payment-response \
          restaurant-approval-request \
          restaurant-approval-response \
          customer
        do
          kafka-topics \
            --bootstrap-server kafka-broker-1:9092 \
            --create \
            --if-not-exists \
            --topic "$${topic}" \
            --replication-factor 3 \
            --partitions 3
        done
        kafka-topics --bootstrap-server kafka-broker-1:9092 --list
    restart: "no"
    networks:
      - food-ordering-system
